services:
  sensitive-check-service:
    build:
      context: .
      dockerfile: Dockerfile
    image: sensitive-check-service:latest
    ports:
      - "3000:3000"
    environment:
      HOST: 0.0.0.0
      PORT: 3000
      NODE_ENV: production
